development:
  adapter: mysql2
  encoding: utf8
  database: shortlink_engine_development
  username: root
  password: ""
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  database: shortlink_engine_test
  username: root
  password: ""
  host: localhost
